module Rosetta.README where
open import Rosetta.CartesianClosed
open import Rosetta.Categories
open import Rosetta.Category
open import Rosetta.DiagramChasing
open import Rosetta.Equality
open import Rosetta.Equivalence
open import Rosetta.Functor
open import Rosetta.Functors
open import Rosetta.HomFunctor
open import Rosetta.Isomorphism
open import Rosetta.NaturalTransformation
open import Rosetta.Prelude
open import Rosetta.Setoids
open import Rosetta.Sets
